- .github/workflows/build-dotnet.yml
- .github/workflows/ci-pipeline.yml
- .github/workflows/test-dotnet.yml
- deployments/docker-compose/docker-compose.yml
- deployments/docker-compose/k8s/deployments.yaml
Testing subscriptions using external websites can lead to confusion because of rate limiting.
Using a self-hosted webhook tester can prevent unwated rate limiting when testing/developing.
Obviously, this is not meant for production and shouldn't be shipped by default when deploying Cloud Streams.
> Added `tarampampam/webhook-tester` in the DockerCompose stack to test subcriptions locally

- src/broker/application/Services/SubscriptionHandler.cs
- src/core/data/Models/Subscriber.cs
- src/gateway/application/Services/CloudEventAdmissionControl.cs
Fixes the SubscriptionHandler to allow only one synchronization loop to operate at a time
> Fixed the SubscriptionHandler to allow only one synchronization loop to operate at a time

- src/dashboard/ui/Pages/CloudEvents/List/Store.cs
- src/dashboard/ui/Pages/CloudEvents/List/View.razor
The events list virtualization was rendering a scroll bar and additional "loading" rows even when a stream/partition had a little number of items and scroll wasn't necessary. 
This is now fixed, the scroll and "loading" elements don't show anymore if not necessary.
> Removed unnecessary scroll when there are less items than available space in the dashboard

- src/core/application/Services/ExceptionHandlingPipelineBehavior.cs
- src/core/infrastructure/event-store/event-store/Assets/Projections/bysource.js
- src/core/infrastructure/event-store/event-store/Assets/Projections/bysubject.js
- src/core/infrastructure/event-store/event-store/Assets/projections/bysubject.js
- src/core/infrastructure/event-store/event-store/CloudStreams.Core.Infrastructure.EventSourcing.EventStore.csproj
- src/core/infrastructure/event-store/event-store/EventStoreProjections.cs
- src/core/infrastructure/event-store/event-store/EventStoreStreams.cs
- src/core/infrastructure/event-store/event-store/Extensions/CloudEventPartitionRefExtensions.cs
- src/core/infrastructure/event-store/event-store/Services/ESCloudEventStore.cs
- Created two new projections:
- by causation id, using metadata's $causationId
- by subject, as it's distinct from $correlationId now
- Changed non "built-in" projections prefix:
- `$by-source-` for per source partitioning (instead of `cloud-events-` before)
- `$by-subject-` for per subject partitioning 
- `$by-causation-` for per causation id partitioning 
- Added support for reading partition type subject, correlation id and causation id
> Enabled reading cloud event stream per correlation or causation id

- .dockerignore
Should fix CI pipeline for Docker Images. The pipeline fails because it cannot find README.md, I guess it's because it's dockerignored.
> fix(CI): Removed README.md from .dockerignore [skip hint]

- deployments/kubernetes/deployment.yaml
- src/core/CloudStreams.Core.Api.Client/CloudStreams.Core.Api.Client.csproj
- src/core/CloudStreams.Core.Api/CloudStreams.Core.Api.csproj
- src/core/CloudStreams.Core.Application/CloudStreams.Core.Application.csproj
- src/core/CloudStreams.Core.Infrastructure.EventSourcing.EventStore/CloudStreams.Core.Infrastructure.EventSourcing.EventStore.csproj
- src/core/CloudStreams.Core.Infrastructure/CloudStreams.Core.Infrastructure.csproj
- src/core/CloudStreams.Core.Infrastructure/Services/DatabaseInitializer.cs
- src/core/CloudStreams.Core/CloudStreams.Core.csproj
- src/gateway/CloudStreams.Gateway.Api/CloudStreams.Gateway.Api.csproj
Updates solution packages, thus resolving Hylo assembly mismatch.
**Notes to maintainers:**
CloudStreams should have its packages updated and should be republished every time a new Hylo version is published to avoid issues with plugins declaring versionless package references
> Updated solution packages

- src/broker/CloudStreams.Broker.Api.Server/CloudStreams.Broker.Api.Server.csproj
- src/broker/CloudStreams.Broker.Api/Configuration/ICloudStreamsApiBuilderExtensions.cs
- src/broker/CloudStreams.Broker.Application/Services/SubscriptionManager.cs
- src/core/CloudStreams.Core.Api.Client/CloudStreams.Core.Api.Client.csproj
- src/core/CloudStreams.Core.Api.Server/CloudStreams.Core.Api.Server.csproj
- src/core/CloudStreams.Core.Api/CloudStreams.Core.Api.csproj
- src/core/CloudStreams.Core.Application/CloudStreams.Core.Application.csproj
- src/core/CloudStreams.Core.Application/Queries/Streams/ReadEventStreamQuery.cs
- src/core/CloudStreams.Core.Infrastructure.EventSourcing.EventStore/CloudStreams.Core.Infrastructure.EventSourcing.EventStore.csproj
- src/core/CloudStreams.Core.Infrastructure/CloudStreams.Core.Infrastructure.csproj
- src/core/CloudStreams.Core/Assets/Definitions/broker.yaml
- src/core/CloudStreams.Core/CloudStreams.Core.csproj
- src/core/CloudStreams.Core/Data/BrokerSpec.cs
- src/gateway/CloudStreams.Gateway.Api.Server/CloudStreams.Gateway.Api.Server.csproj
- src/gateway/CloudStreams.Gateway.Api/CloudStreams.Gateway.Api.csproj
- Adds the capability to the Broker to perform label-based filtering of subscriptions
- Updates solution packages to latest version
> Added the capability to the Broker to perform label-based filtering of subscriptions

- src/dashboard/CloudStreams.Dashboard/Components/Timeline/State.cs
- src/dashboard/CloudStreams.Dashboard/Components/Timeline/Store.cs
- src/dashboard/CloudStreams.Dashboard/Components/Timeline/Timeline.razor
- src/dashboard/CloudStreams.Dashboard/Services/EventDropsInterop.cs
- src/dashboard/CloudStreams.Dashboard/wwwroot/js/event-drops-interop.js
Currently when the user changes timeline parameters, the time range stays the same. It can be a good thing when adding a new stream for a stream comparison for instance, but it can also be misleading as the events count displayed doesn't change:
This PR adds the opportunity for the user to define if they want to keep the currently displayed time frame or recompute it based on the dataset start and end (after modifying the timeline parameters).
> Improved Dashboard timeline time range management

- src/core/CloudStreams.Core.Api.Client/Services/CloudStreamsCoreApiClient.CloudEvents.cs
Fixed the format of the partition related parameters in the API client.
Closes #64
> Fixed partition query parameters format in API client

- src/core/CloudStreams.Core.Api.Client/Services/CloudStreamsCoreApiClient.CloudEvents.cs
- src/core/CloudStreams.Core.Api/Controllers/CloudEventPartitionsController.cs
Fixed both the API action and its client to support `/` in the partition id when querying metadata.
Closes #66
> Handled requesting metadata for partitions with id containing `/`

- src/core/CloudStreams.Core.Application/Extensions/CloudEventRecordExtensions.cs
Fixes the CloudEventRecordExtensions to filter out non-standard, unsupported cloud event attributes
Fixes #63
> Fix the CloudEventRecordExtensions to filter out non-standard, unsupported cloud event attributes

- .github/workflows/build-dotnet.yml
- .github/workflows/publish.yml
- .github/workflows/test-dotnet.yml
- CloudStreams.sln
- src/core/CloudStreams.Core/HorizonEvaluationMode.cs
- src/core/CloudStreams.Core/HorizonTrackingMode.cs
- src/core/CloudStreams.Core/LoopAction.cs
- src/core/CloudStreams.Core/Resources/GatewaySpec.cs
- src/core/CloudStreams.Core/Resources/RetryPolicy.cs
- src/core/CloudStreams.Core/Resources/SplitHorizonPolicy.cs
- src/gateway/CloudStreams.Gateway.Application/Services/CloudEventAdmissionControl.cs
- Adds a new `SplitHorizon` property to the `Subscription` resource spec, used to configure the split-horizon policy to use, if any
> Add a new `SplitHorizon` property to the `Subscription` resource spec, used to configure the split-horizon policy to use, if any

- src/core/CloudStreams.Core.Api.Client/Services/ResourceManagementApi.cs
- src/core/CloudStreams.Core.Api/ClusterResourceApiController.cs
- src/core/CloudStreams.Core.Application/Commands/Resources/Generic/PatchResourceStatusCommand.cs
- src/core/CloudStreams.Core.Application/Commands/Resources/PatchResourceStatusCommand.cs
- src/core/CloudStreams.Core.Application/Extensions/IServiceCollectionExtensions.cs
- Adds a new endpoint to the `ClusterResourceApiController`, used to patch a resource's status
- Fixes the `ResourceManagementApi` to call the proper endpoint when attempting to patch the status of a resource
> Repaired the ability to recover a faulted subscription without restart

- deployments/docker-compose/config/subscriptions/all.yaml
- deployments/docker-compose/docker-compose.dcproj
- deployments/docker-compose/docker-compose.yml
- src/broker/CloudStreams.Broker.Application/Services/SubscriptionHandler.cs
- Fixes the `SubscriptionHandler` service by enforcing a single initialization loop, and by properly catching cancellation-related exceptions
- Fixes the `SubscriptionHandler` to only attempt resolving a stream's offset after making sure the stream exists
- Fixes the `SubscriptionHandler` to attempt catching up also when the `Subscription`'s `observedGeneration` is null, which means that the stream never was processed
> Fix the `SubscriptionHandler` service

- src/dashboard/CloudStreams.Dashboard/Components/ResourceEditor/ResourceEditor.razor
Previously, the editor panel retained an outdated version of a resource if its `qualifiedName` remained unchanged (compare to the one edited previously). This caused users to see stale data when reopening the editor after an external update. Now, the editor checks the entire resource instead of just `qualifiedName`, ensuring it always loads the latest version.
**Special notes for reviewers**:
**Additional information (if needed):**
> Refresh editor panel with updated resource in the Dashboard

- .gitignore
- src/broker/CloudStreams.Broker.Application/Services/SubscriptionHandler.cs
- src/core/CloudStreams.Core/Resources/SubscriberStatus.cs
- src/core/CloudStreams.Core/Resources/SubscriptionStatus.cs
- src/core/CloudStreams.Core/SubscriberStatus.cs
* Adds a new `Subscriber` property to the `SubscriptionStatus`, used to describe the reachability of the configured subscriber
* Updates the `SubscriptionHandler`to set the subscriber's state and reason
> Add a new `Subscriber` property to the `SubscriptionStatus`, used to describe the reachability of the configured subscriber

- src/dashboard/CloudStreams.Dashboard.StateManagement/ComponentStore.cs
- src/dashboard/CloudStreams.Dashboard/Components/AutoRefreshForm/AutoRefreshForm.razor
- src/dashboard/CloudStreams.Dashboard/Components/ReadOptionsForm/ReadOptionsForm.razor
- src/dashboard/CloudStreams.Dashboard/Components/ReadOptionsForm/Store.cs
- src/dashboard/CloudStreams.Dashboard/Components/Timeline/Store.cs
- src/dashboard/CloudStreams.Dashboard/Components/Timeline/Timeline.razor
- src/dashboard/CloudStreams.Dashboard/Pages/CloudEvents/List/Store.cs
- src/dashboard/CloudStreams.Dashboard/Pages/CloudEvents/List/View.razor
- src/dashboard/CloudStreams.Dashboard/Refresher.cs
- src/dashboard/CloudStreams.Dashboard/StatefulComponent.cs
- Fixed an issue where the last event in the table was incorrectly removed when new events arrived if the stream length was initially smaller than the table’s capacity.
- Now, the system updates the stream length before reloading the table, ensuring accurate event display.
- This also optimizes performance by reducing unnecessary data fetches in the stream length stay unchanged.
- Improved the UI controls for configuring auto-refresh intervals, making them more user-friendly.
**Special notes for reviewers**:
**Additional information (if needed):**
> Improve events auto-refresh in the Dashboard

- src/dashboard/CloudStreams.Dashboard/Components/Timeline/TimelineCloudEventDetails.razor
- src/dashboard/CloudStreams.Dashboard/Pages/CloudEvents/List/View.razor
- Fixes the display of CloudEvents source by using the URI's original string instead of its string representation
> Fix the display of CloudEvents source by using the URI's original string instead of its string representation

- src/dashboard/CloudStreams.Dashboard/Pages/Subscriptions/List/View.razor
Move the subscriber status tag to its own column in the Dashboard subscribers' list.
Closes #103 
**Special notes for reviewers**:
**Additional information (if needed):**
> Move the subscriber status tag to its own column in the Dashboard

- src/dashboard/CloudStreams.Dashboard/Components/AutoRefreshForm/AutoRefreshForm.razor
- src/dashboard/CloudStreams.Dashboard/Components/ReadOptionsForm/ReadOptionsForm.razor
- src/dashboard/CloudStreams.Dashboard/Components/ResourceEditor/ResourceEditor.razor
- src/dashboard/CloudStreams.Dashboard/Components/ResourceManagement/ResourceManagementComponent.cs
- src/dashboard/CloudStreams.Dashboard/Components/ResourceManagement/ResourceManagementComponentState.cs
- src/dashboard/CloudStreams.Dashboard/Components/ResourceManagement/ResourceManagementComponentStore.cs
- src/dashboard/CloudStreams.Dashboard/Components/ResourceManagement/ResourcesFilter.cs
- src/dashboard/CloudStreams.Dashboard/Components/Timeline/Timeline.razor
- src/dashboard/CloudStreams.Dashboard/Pages/CloudEvents/List/View.razor
- src/dashboard/CloudStreams.Dashboard/Pages/Subscriptions/List/State.cs
- src/dashboard/CloudStreams.Dashboard/Pages/Subscriptions/List/Store.cs
- src/dashboard/CloudStreams.Dashboard/Pages/Subscriptions/List/SubscriptionListItem.cs
- src/dashboard/CloudStreams.Dashboard/Pages/Subscriptions/List/View.razor
- src/dashboard/CloudStreams.Dashboard/StatefulComponent.cs
Adds a "Length" column to the Subscriptions list, displaying the total length of the stream/partition the subscription consumes.
Note that filters do not apply. If a partition contains N items and the subscription filters out half of them, the displayed length will still be N, not N/2.
Closes #87
**Special notes for reviewers**:
**Additional information (if needed):**
> Add offset/length of stream/partition a persistent subscription consumes in the Dashboard
